### PR TITLE
refactor: use submodules

### PR DESCRIPTION
**Pull request by oSumAtrIX**
This WIP PR gets rid of the `src.zip` file. Instead, it uses submodules to get all the required sources. 

- The import path in `src\base\tools\aapt2\Resources.proto` has to be manually changed.
- The wrong `protoc` version is used in my case. The header files won't be compatible.
- A patch has to be applied from `patches`

### CODE REVIEW

**Comment by Sculas** [comment]
I have a better idea for this. If it doesn't work out I'll merge this, otherwise I'll be using my idea since that doesn't need all of the submodules.

**Comment by oSumAtrIX** [comment]
This PR is still a draft, it's not working yet and would need to be fixed before merging it

**Comment by Sculas** [comment]
This PR is *~~slightly~~* messed up. Redo this PR in a new one if you want to continue it, and make sure to not rebase as it screwed up the Git history :P

**Comment by oSumAtrIX** [comment]
Still a draft, the history has to be deleted due to the zip file being in there

**Comment by Sculas** [comment]
No, it does not matter if the zip file is in history. It's fine, let it be. It's not the end of the world, not yet at least.

**Pull request closed without merging**
